### ISSUE TITLE
Formatting and parsing using the US format not symmetric

### ISSUE THREAD

**Issue by olivergierke** [JavaMoney/javamoney-examples#12] opened 2015-01-13 12:57 UTC
A `Money` instance written in the US format cannot be parsed again using the very same format.

In [this example](https://github.com/JavaMoney/javamoney-examples/blob/master/functional-example/src/main/java/org/javamoney/funcional/example/FormatExample.java) add the following line to see it fail:

```java
Money.parse(usFormat.format(monetaryAmount), usFormat);
```

Using the German format works fine though.

**Comment by stokito** [comment] 2015-01-13 13:08
Any tests cases exists to catch this issue? If not, we should first create it and then fix

**Comment by olivergierke** [comment] 2015-01-13 13:08
Using the UK locale is broken, too.

**Comment by stokito** [comment] 2015-01-13 13:09
OK, I can't check right now but assign a bug label

**Comment by keilw** [comment] 2015-01-14 20:41
I'm not sure, if it's subject to examples, but ideally we should have a unit test iterating all available locales...

**Comment by olivergierke** [comment] 2015-01-14 20:53
Agree that it probably has to be fixed in the reference implementation but I couldn't find the tracker for that quickly and didn't want to forget about the glitch :).

**Comment by atsticks** [comment] 2015-01-14 22:11
I have to look at it. If I remember correctly there should a similar test
in the Tck, which afaik currently is failing...

We will do a hackergarten next week. Hope we have time to fix it then...

Anatole


Oliver Gierke <notifications@github.com> schrieb am Mi., 14. Jan. 2015 um
21:53:

**Comment by keilw** [comment] 2015-07-19 21:41
Is this still open? @olivergierke If you still face the problem, please file a JIRA ticket here: https://java.net/jira/browse/javamoney/ (same place as most JSRs ;-) RI is just being broken into modules for 1.0.1, we'd love to fix issues with that release if they are filed soon enough.

**Comment by olivergierke** [comment] 2015-07-20 06:21
I cannot reproduce the error with Moneta 1.0. Seems to be fixed, thanks!

**Comment by keilw** [comment] 2015-07-20 07:03
Thanks, then we can close it here. Feel free to open something in JIRA if you spot something else.

**Closed by keilw** 2015-07-20 07:03 UTC
Labels: bug

**Comment by atsticks** [comment] 2015-07-20 18:01
Yep. Afaik I also added a corredponding test. Mabe even as part of the tck, but I dot yet remember it exactly...
CheersAnatole


Von meinem Samsung Galaxy Smartphone gesendet.-------- Ursprüngliche Nachricht --------Von: Oliver Gierke <notifications@github.com> Datum: 20.07.2015  08:21  (GMT+01:00) An: JavaMoney/javamoney-examples <javamoney-examples@noreply.github.com> Cc: Anatole Tresch <atsticks@gmail.com> Betreff: Re: [javamoney-examples] Formatting and parsing using the US format
  not symmetric (#12) 
I cannot reproduce the error with Moneta 1.0. Seems to be fixed, thanks!
